= Как ещё искать ошибки, в исходниках, если все предупреждения компилятора уже почищены

Пробуем скомпилировать программу с опциями `-Wall -Wextra`, вызвав `make`.
Компилятор *gcc* не сообщает о каких-либо ошибках или предупреждениях.
Однако данная программа содержит достаточно много проблем.

Данная программа печатает список файлов в директории, путь до которой определяется следующим образом:

* Если при запуске передан 1 аргумент, то он рассматривается как путь
до директории, содержимое которой нужно показать
* Если число переданных аргументов не 1, то путь берётся из переменной окружения `HOME`
* Если число переданных аргументов не 1, и в переменной окружения
`HOME` ничего нет, то в качестве пути берётся `/`

Кажется, что программа работает, как ожидалось:

[source, shell]
----
./main .
----

[source, shell]
----
./main
----

Но видим неожиданное поведение (кроме списка файлов напечатается *Hacked*), если выполнить программу с таким аргументам

[source, shell]
----
./main ".;echo Hacked"
----

Т.е. компилятор не рассказал о всех проблемах в коде. Но о них могут подсказать линтеры.
Рассмотрим, что могут сказать линтеры об этом коде:

* *clang-tidy*

[source, shell]
----
make clang-tidy
----

* *flawfinder*

[source, shell]
----
make flawfinder
----

Flowfinder сообщает о множестве потенциальных проблем, в том числе о проблеме, описанной в https://cwe.mitre.org/data/definitions/78.html[CWE-78].
Убедимся, что наша программа уязвима:
```bash
./main ".;echo Hacked"
```

Кроме распечатывания содержимого текущей директории, была выполнена команда `echo Hacked`, т.е есть способ передавать через аргумент произвольный shell-код, который будет исполнен.

== Попробуйте самостоятельно

Попробуйте прогнать эту программу ещё через какой-нибудь статический анализатор, найти список анализаторов можно гугля по словам `<язык программирования> static analyzer`.

== Рекомендации

* Автоматизируйте проверки своего кода статическими анализаторами в своей системе CI/CD.
* Также довольно легко можно включить проверки подключив к своему репозиторию https://www.codefactor.io/[CodeFactor](список поддерживаемых языков довольно большой, скорее всего подойдёт для вашего проекта).

